"""Added BankingOfficer model and updated Application model

Revision ID: 8495075d54c8
Revises: 
Create Date: 2024-08-25 14:14:04.919429

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8495075d54c8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.add_column(sa.Column('reviewed_by', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'banking_officer', ['reviewed_by'], ['officer_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('application', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('reviewed_by')

    # ### end Alembic commands ###
